### ISSUE TITLE
fix: don't sort conditions

### ISSUE THREAD

**Issue by dmnsgn** [privatenumber/pkg-entry-points#3]
Quoting node.js:
> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

Is there any specific reason to sort the conditions here?

https://github.com/privatenumber/pkg-entry-points/blob/de646e24b1b7cca10bc829ee20d08fe38562ed19/src/index.ts#L186

**Comment by privatenumber** [comment]
It's sorting it to give the least specific exports first.

Closing this because there's no bug, and it seems like something you can confirm by running it yourself.

**Comment by dmnsgn** [comment]
So just to confirm, given the following package:
```json
{
  "name": "@emotion/react",
  "exports": {
    // ...
    "./jsx-runtime": {
      "module": {
        "worker": "./jsx-runtime/dist/emotion-react-jsx-runtime.worker.esm.js",
        "browser": "./jsx-runtime/dist/emotion-react-jsx-runtime.browser.esm.js",
        "default": "./jsx-runtime/dist/emotion-react-jsx-runtime.esm.js"
      },
      "import": "./jsx-runtime/dist/emotion-react-jsx-runtime.cjs.mjs",
      "default": "./jsx-runtime/dist/emotion-react-jsx-runtime.cjs.js"
    }
    // ...
  }
}
```

the following is the correct behaviour and matches node.js expectations:

```js
import { getPackageEntryPoints } from "pkg-entry-points";

const packageExports = await getPackageEntryPoints("./node_modules/@emotion/react");
console.log(packageExports['./jsx-runtime']);

// =>
[
  [
    [ 'import' ],
    './jsx-runtime/dist/emotion-react-jsx-runtime.cjs.mjs'
  ],
  [
    [ 'default' ],
    './jsx-runtime/dist/emotion-react-jsx-runtime.cjs.js'
  ],
  [
    [ 'module', 'worker' ],
    './jsx-runtime/dist/emotion-react-jsx-runtime.worker.esm.js'
  ],
  [
    [ 'browser', 'module' ],
    './jsx-runtime/dist/emotion-react-jsx-runtime.browser.esm.js'
  ],
  [
    [ 'default', 'module' ],
    './jsx-runtime/dist/emotion-react-jsx-runtime.esm.js'
  ]
]
```

eg.:
- the "module" key, although first in the list, gets pushed at the end of the list because it is not one of the node.js supported keys ("node-addons", "node", "import", "require", "default") 
- the "module" and worker/browser/default sub conditions are also reordered

**Comment by privatenumber** [comment]
So this package just lists the possible entry points and the possible combinations of conditions. When specifying the conditions as a user, the order of import conditions does not matter.

That's to say these are the same thing:
```
node -C module -C worker file.js
```

```
node -C worker -C module file.js
```

Like it says in the Node.js spec you cited, the order that matters is in their `package.json`.

FYI the sorting you referenced is sorting that outer array, not the order of conditions.
