### ISSUE TITLE
Provide additional sync API

### ISSUE THREAD

**Issue by simonihmig** [privatenumber/pkg-entry-points#4]
### Feature request

Would you consider exposing a sync API, like `getPackageEntryPointsSync`?

I already have a spike of that working locally, so happy to provide a PR!

### Motivations

For reasons I have no influence over, I need to use this in a sync context.

### Alternatives

No workaround possible to call async in sync context, other than very hacky things.

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Oh thats cool! Thanks for offering.

Would you mind throwing up a quick PR?

Im mainly concerned about how much code it adds, complexity, and maintenance so just want to get an idea.

**Comment by simonihmig** [comment]
Sure, here is a draft PR: https://github.com/privatenumber/pkg-entry-points/pull/5

So far, I have basically duplicated the two functions, removed all async/await and replaced the `fs` calls with their sync counterparts. Haven't worked yet on test coverage, but I think we should be able to basically run the existing test suite on the sync APIs without much duplication (as `await` on a sync call does no harm). Also maybe there is some way to DRY this up a bit, haven't looked into that yet...

**Comment by simonihmig** [comment]
@privatenumber did you have a chance to look into that PR?

**Comment by privatenumber** [comment]
Sorry for the late response and thanks for the ping!

Yes, doesn't look like too much code! Thanks

**Comment by simonihmig** [comment]
@privatenumber I updated the PR to cover the new sync API in (existing) tests, and a bit of cleanup. Should be ready for review now! 🙂
